// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.15.8
// source: v1/heartbeat.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHeartbeatPONE = "/v1.Heartbeat/PONE"

type HeartbeatHTTPServer interface {
	PONE(context.Context, *emptypb.Empty) (*PONEResponse, error)
}

func RegisterHeartbeatHTTPServer(s *http.Server, srv HeartbeatHTTPServer) {
	r := s.Route("/")
	r.GET("/heartbeat", _Heartbeat_PONE0_HTTP_Handler(srv))
}

func _Heartbeat_PONE0_HTTP_Handler(srv HeartbeatHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHeartbeatPONE)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PONE(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PONEResponse)
		return ctx.Result(200, reply)
	}
}

type HeartbeatHTTPClient interface {
	PONE(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *PONEResponse, err error)
}

type HeartbeatHTTPClientImpl struct {
	cc *http.Client
}

func NewHeartbeatHTTPClient(client *http.Client) HeartbeatHTTPClient {
	return &HeartbeatHTTPClientImpl{client}
}

func (c *HeartbeatHTTPClientImpl) PONE(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*PONEResponse, error) {
	var out PONEResponse
	pattern := "/heartbeat"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHeartbeatPONE))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
