service:
  id: link_1
  name: micro.link.service
  version: v1.0
server:
  http:
    addr: 0.0.0.0:20000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:21000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:Abc0331#@tcp(127.0.0.1:3306)/micro-server?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
