// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type UuidHTTPServer interface {
	GenerateUuid(context.Context, *GenerateUuidRequest) (*GenerateUuidReply, error)
}

func RegisterUuidHTTPServer(s *http.Server, srv UuidHTTPServer) {
	r := s.Route("/")
	r.POST("/uuid/generate", _Uuid_GenerateUuid0_HTTP_Handler(srv))
}

func _Uuid_GenerateUuid0_HTTP_Handler(srv UuidHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateUuidRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.uuid.v1.Uuid/GenerateUuid")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateUuid(ctx, req.(*GenerateUuidRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateUuidReply)
		return ctx.Result(200, reply)
	}
}

type UuidHTTPClient interface {
	GenerateUuid(ctx context.Context, req *GenerateUuidRequest, opts ...http.CallOption) (rsp *GenerateUuidReply, err error)
}

type UuidHTTPClientImpl struct {
	cc *http.Client
}

func NewUuidHTTPClient(client *http.Client) UuidHTTPClient {
	return &UuidHTTPClientImpl{client}
}

func (c *UuidHTTPClientImpl) GenerateUuid(ctx context.Context, in *GenerateUuidRequest, opts ...http.CallOption) (*GenerateUuidReply, error) {
	var out GenerateUuidReply
	pattern := "/uuid/generate"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.uuid.v1.Uuid/GenerateUuid"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
