// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.4

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ShortLinkHTTPServer interface {
	GenerateShortLink(context.Context, *GenerateShortLinkRequest) (*GenerateShortLinkReply, error)
}

func RegisterShortLinkHTTPServer(s *http.Server, srv ShortLinkHTTPServer) {
	r := s.Route("/")
	r.POST("/link/short/generate", _ShortLink_GenerateShortLink0_HTTP_Handler(srv))
}

func _ShortLink_GenerateShortLink0_HTTP_Handler(srv ShortLinkHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateShortLinkRequest
		if err := ctx.Bind(&in.Url); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.link.v1.ShortLink/GenerateShortLink")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateShortLink(ctx, req.(*GenerateShortLinkRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateShortLinkReply)
		return ctx.Result(200, reply)
	}
}

type ShortLinkHTTPClient interface {
	GenerateShortLink(ctx context.Context, req *GenerateShortLinkRequest, opts ...http.CallOption) (rsp *GenerateShortLinkReply, err error)
}

type ShortLinkHTTPClientImpl struct {
	cc *http.Client
}

func NewShortLinkHTTPClient(client *http.Client) ShortLinkHTTPClient {
	return &ShortLinkHTTPClientImpl{client}
}

func (c *ShortLinkHTTPClientImpl) GenerateShortLink(ctx context.Context, in *GenerateShortLinkRequest, opts ...http.CallOption) (*GenerateShortLinkReply, error) {
	var out GenerateShortLinkReply
	pattern := "/link/short/generate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.link.v1.ShortLink/GenerateShortLink"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Url, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
