// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"mt/config"
	"mt/internal/biz"
	"mt/internal/data"
	"mt/internal/server"
	"mt/internal/service"
	"mt/pkg/logger"
	"mt/pkg/repositories"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(configServer *config.Server, configData *config.Data, loggerLogger *logger.Logger) (*kratos.App, func(), error) {
	dataRepo := repositories.NewDataRepo(loggerLogger, configData)
	dataData, cleanup, err := data.NewData(configData, loggerLogger, dataRepo)
	if err != nil {
		return nil, nil, err
	}
	heartbeatRepo := data.NewHeartbeatRepo(dataData, loggerLogger)
	heartbeatUsecase := biz.NewHeartbeatUsecase(heartbeatRepo, loggerLogger)
	heartbeatService := service.NewHeartbeatService(heartbeatUsecase)
	articleRepo := data.NewArticleRepo(dataData, loggerLogger)
	articleUsecase := biz.NewArticleUsecase(articleRepo, loggerLogger)
	articleService := service.NewArticleService(articleUsecase)
	grpcServer := server.NewGRPCServer(configServer, heartbeatService, articleService, loggerLogger)
	httpServer := server.NewHTTPServer(configServer, heartbeatService, articleService, loggerLogger)
	app := newApp(loggerLogger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
