// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"link_service/internal/biz"
	"link_service/internal/conf"
	"link_service/internal/data"
	"link_service/internal/server"
	"link_service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	shortLinkRepo := data.NewShortLinkRepo(dataData, logger)
	shortLinkUsecase := biz.NewShortLinkUsecase(shortLinkRepo, logger)
	shortLinkService := service.NewShortLinkService(shortLinkUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, shortLinkService, logger)
	grpcServer := server.NewGRPCServer(confServer, shortLinkService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
